version: ~> 1.0

import:
  - silverstripe/silverstripe-travis-shared:config/provision/standard-jobs-range.yml

env:
  global:
    - COMPOSER_ROOT_VERSION="3.x-dev"
    - REQUIRE_EXTRA="symbiote/silverstripe-queuedjobs:^4.0"

jobs:
  include:
    - php: 7.4
      env:
        - DB=MYSQL
        - REQUIRE_INSTALLER=4.x-dev
        - PHPUNIT_TEST=1
        - REQUIRE_EXTRA="symbiote/silverstripe-queuedjobs:^4 silverstripe/subsites:^2"
